production:
  delivery_method: :smtp
  smtp_settings:
    address: "smtp.sendgrid.net"
    port: 25
    authentication: :plain
    domain: "heroku.com"
    user_name: <%= ENV["SENDGRID_USERNAME"] %>
    password: <%= ENV["SENDGRID_PASSWORD"] %>
